[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "cd frontend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
